"""Report generation — markdown (human) and JSON (machine)."""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path

from painscout.models import Report


def render_markdown(report: Report, analyzer_mode: str) -> str:
    lines: list[str] = []
    lines.append("# 🔍 PainScout Report")
    lines.append("")
    lines.append(f"- **Query:** `{report.query}`")
    lines.append(f"- **Generated:** {report.generated_at}")
    lines.append(f"- **Pain points scanned:** {len(report.pain_points)}")
    lines.append(f"- **Analyzer:** {'AI (LLM)' if analyzer_mode == 'ai' else 'heuristic fallback'}")
    lines.append("")

    counts: dict[str, int] = {}
    for p in report.pain_points:
        counts[p.source] = counts.get(p.source, 0) + 1
    lines.append("**Sources:** " + ", ".join(f"{k}: {v}" for k, v in sorted(counts.items())))
    lines.append("")

    if not report.opportunities:
        lines.append("No opportunities found — try a different query or more sources.")
        return "\n".join(lines)

    lines.append(f"## 🎯 Top {len(report.opportunities)} Opportunities")
    lines.append("")
    for i, opp in enumerate(report.opportunities, 1):
        head = f"### {i}. [{opp.score:.0f}/100] {opp.theme}"
        if opp.trend:
            head += f"  · 🔺 {opp.trend}"
        lines.append(head)
        lines.append("")
        lines.append(f"**The pain:** {opp.pain}")
        lines.append("")
        lines.append("**Evidence:**")
        for e in opp.evidence:
            lines.append(f"- “{e}”")
        lines.append("")
        lines.append(f"**Sources:** {', '.join(opp.sources)} · [best link]({opp.url})")
        lines.append("")
        lines.append(f"**AI solution to build:** {opp.suggested_solution}")
        lines.append("")
        lines.append(f"**How to charge:** {opp.monetization}")
        if opp.market:
            mk = opp.market
            lines.append("")
            lines.append(f"**Competition:** {mk.get('level', 'unknown').upper()}")
            if mk.get("existing"):
                lines.append("- " + "\n- ".join(str(x) for x in mk["existing"][:5]))
            if mk.get("note"):
                lines.append(f"  ({mk['note']})")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by PainScout — deploy an AI SaaS or WhatsApp automation to fix these.*")
    return "\n".join(lines)


def render_json(report: Report) -> str:
    return json.dumps(report.to_dict(), indent=2, ensure_ascii=False)


def save_report(report: Report, analyzer_mode: str, out_dir: Path) -> tuple[Path, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(UTC).strftime("%Y%m%d_%H%M")
    md_path = out_dir / f"pain-report_{stamp}.md"
    json_path = out_dir / f"pain-report_{stamp}.json"
    md_path.write_text(render_markdown(report, analyzer_mode), encoding="utf-8")
    json_path.write_text(render_json(report), encoding="utf-8")
    # Keep a stable "latest" copy for the GitHub repo landing page.
    (out_dir / "latest.md").write_text(render_markdown(report, analyzer_mode), encoding="utf-8")
    (out_dir / "latest.json").write_text(render_json(report), encoding="utf-8")
    return md_path, json_path
